### PR TITLE
Added  NLM JATS disp-quote support

### PR DESCRIPTION
**Pull request by withanage**
Added disp-quote support for nlm-jats conveter.
Spec: http://jats.nlm.nih.gov/publishing/tag-library/1.1d3/element/disp-quote.html
Node model "quotation"

### CODE REVIEW

**Comment by michael** [comment]
Thanks @withanage! Looking very good already. Maybe you could cleanup the CSS a bit.

Regarding the type name: Is 'quotation' the best option, or should we just call it 'quote'?

**Comment by withanage** [comment]
@michael , thanks for the comments Changed quotation to quote and cleaned the css.

**Comment by michael** [comment]
Thanks Dulip! Don't want to nitpick, but maybe you can unify the indentation level to 2 spaces (you mixed 2 and 4)?

Thanks!  Will test this soon and merge.

**Comment by withanage** [comment]
Oops, sorry for that. Yes, my indentation was set to 4 and now corrected.

**Comment by michael** [comment]
Hey sorry I still didn't get to review this at runtime. Can you provide me a link again with an XML that has a quote in it? Just want to have it running once and then merge it immediately. Thanks!

**Comment by withanage** [comment]
Here is a test example.
http://heiup.uni-heidelberg.de/reader/index/43/example.xml
But I will put a real example here in our omp front end application, when our next book is published.
https://github.com/UB-Heidelberg/UBHD-OMPPortal#demo

**Comment by michael** [comment]
:+1:

**Pull request merged**
