### PR TITLE
improve zoom

### PR DESCRIPTION
**Pull request by pkra**
add padding (compensates for horizontal scrollbar size); add simple UI for shrunk equations.

### CODE REVIEW

**Comment by michael** [comment]
Nice addition. Tested and works. I would probably show the zoom icon always not just below the 0.9 threshold. Alternatively, zooming option could be disabled for >=0.9 in general.

**Comment by michael** [comment]
I found another edge case: when you resize the window before all math elements have been rendered there will be an error in the fitFormula method since the `mathEl` can not be looked up.

After: 

```js
var mathEl = $(formulaNode).find('.math')[0];
```

please add

```js
if (!mathEl) return;
```

**Comment by pkra** [comment]
> I would probably show the zoom icon always not just below the 0.9 threshold.
>  Alternatively, zooming option could be disabled for >=0.9 in general.

The reason for the former is the latter. Without the threshold, all display equations would get the zoom-in cursor. Perhaps the "zoom/unshrink" can be implemented as a class? That way it's easier to customize, too.

> when you resize the window before all math elements have been rendered there will be an error in the fitFormula method since the mathEl can not be looked up.

Ah, right.  Like so?

**Comment by michael** [comment]
Implementation is fine for now I would say. As a matter of consistency I just wanted to state that if there's no zoom cursor (>=0.9) there should also be no zoom action. However to implement this, we would need to evaluate the ratio within the `toggleFormulaScaling` for instance.

```js
  this.isFormulaZoomable = function(nodeId) {
    return this.getFormulaScaleRatio(nodeId) < 0.9;
  }

  this.toggleFormulaScaling = function(event, node) {
    var nodeId = $(node).find('.MathJax').attr("id");
    var formulaNode = $(node).parents('.content-node.formula')[0];
    if (this.isFormulaZoomable) {
      this.toggleFormulaIsZoomed(nodeId);
      this.fitFormula(nodeId, formulaNode);
    }
  };
```

Ok maybe we should have this in a workflow class soon. Then we don't need to maintain a branch of the lens module. I will merge this pull request for now. It's demoable I would say.

**Comment by pkra** [comment]
> I will merge this pull request for now. It's demoable I would say.

Ok.

**Pull request merged**
